### ISSUE TITLE
'getString ' method does not return null

### ISSUE THREAD

**Issue by ghost** [Flugins/CommandBook#1]
https://github.com/Flugins/CommandBook/blob/05d7f84c9dbb5937d37dea71dc29233393cc6726/src/Flugins/CommandBook/CommandBook.php#L23
'getString ' method does not return null.

Reference:
https://github.com/pmmp/NBT/blob/1a73be856840e521ff27bbdcfa44b1f54fb30892/src/tag/CompoundTag.php#L197

**Comment by PrestigeLulu** [comment]
By referring to the issue, the error was fixed and the code was improved.
